version: '3'
services:
  py:
    image: python:3.7
    container_name: pyt
    ports:
     - 80:80
    volumes:
     - ./src:/usr/src
    working_dir: /usr/src
    command: /bin/sh -c "pip install -r requirements.txt && python main.py"
    tty: true
